-- MySQL Script generated by MySQL Workbench
-- Thu Dec 18 09:55:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opizza
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `opizza` ;

-- -----------------------------------------------------
-- Schema opizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opizza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_slovak_ci ;
USE `opizza` ;

-- -----------------------------------------------------
-- Table `opizza`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`categories` ;

CREATE TABLE IF NOT EXISTS `opizza`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`products` ;

CREATE TABLE IF NOT EXISTS `opizza`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `is_available` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`sizes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`sizes` ;

CREATE TABLE IF NOT EXISTS `opizza`.`sizes` (
  `size_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `weight_grams` INT NOT NULL,
  `sort_order` INT NULL DEFAULT NULL,
  PRIMARY KEY (`size_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`product_variants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`product_variants` ;

CREATE TABLE IF NOT EXISTS `opizza`.`product_variants` (
  `variant_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`variant_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `opizza`.`ingredients` (
  `ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `is_spicy` TINYINT NULL DEFAULT FALSE,
  `is_fish` TINYINT NULL DEFAULT NULL,
  `if_meat` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`ingredient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`product_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`product_ingredients` ;

CREATE TABLE IF NOT EXISTS `opizza`.`product_ingredients` (
  `product_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `ingredient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`tags` ;

CREATE TABLE IF NOT EXISTS `opizza`.`tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `color_hex` VARCHAR(7) NULL DEFAULT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`product_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`product_tags` ;

CREATE TABLE IF NOT EXISTS `opizza`.`product_tags` (
  `product_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`users` ;

CREATE TABLE IF NOT EXISTS `opizza`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'GUEST',
  `avatar_url` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `is_active` TINYINT NULL DEFAULT NULL,
  `default_address_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`addresses` ;

CREATE TABLE IF NOT EXISTS `opizza`.`addresses` (
  `addresses_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `city` VARCHAR(30) NULL DEFAULT NULL,
  `zip_code` VARCHAR(6) NULL DEFAULT NULL,
  `street` VARCHAR(100) NULL DEFAULT NULL,
  `house` VARCHAR(10) NULL DEFAULT NULL,
  `flat` VARCHAR(5) NULL DEFAULT NULL,
  `type` VARCHAR(64) NULL DEFAULT NULL,
  `is_default` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`addresses_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`carts` ;

CREATE TABLE IF NOT EXISTS `opizza`.`carts` (
  `carts_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`carts_id`),
  INDEX `fk_carts_users_idx` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`cart_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`cart_items` ;

CREATE TABLE IF NOT EXISTS `opizza`.`cart_items` (
  `cart_items_id` INT NOT NULL AUTO_INCREMENT,
  `cart_id` INT NOT NULL,
  `product_variant_id` INT NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`cart_items_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`orders` ;

CREATE TABLE IF NOT EXISTS `opizza`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `total_price` DECIMAL(10,2) NOT NULL,
  `note` TINYTEXT NULL DEFAULT NULL,
  `delivery_address_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opizza`.`order_items` ;

CREATE TABLE IF NOT EXISTS `opizza`.`order_items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_variant_id` INT NULL DEFAULT NULL,
  `quantity` INT NOT NULL,
  `price_at_order` DECIMAL(10,2) NOT NULL,
  `product_name_at_order` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
