-- MySQL Script generated by MySQL Workbench
-- Finalized version - December 15, 2025
-- Compact format for direct SQL execution

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opizza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_slovak_ci;
USE `opizza`;

-- -----------------------------------------------------
-- Table `opizza`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`categories` ( `category_id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(50) NOT NULL, `description` TEXT NULL, `sort_order` INT NULL, PRIMARY KEY (`category_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`products` ( `product_id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(100) NOT NULL, `description` TEXT NULL, `image_url` VARCHAR(255) NOT NULL, `category_id` INT NULL, `is_available` TINYINT DEFAULT TRUE NULL, PRIMARY KEY (`product_id`), INDEX `fk_products_categories_idx` (`category_id` ASC) VISIBLE, CONSTRAINT `fk_products_categories` FOREIGN KEY (`category_id`) REFERENCES `opizza`.`categories` (`category_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`sizes` ( `size_id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(20) NOT NULL, `weight_grams` INT NOT NULL, `sort_order` INT NULL, PRIMARY KEY (`size_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`product_variants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`product_variants` ( `variant_id` INT NOT NULL AUTO_INCREMENT, `product_id` INT NOT NULL, `size_id` INT NOT NULL, `price` DECIMAL(10,2) NOT NULL, PRIMARY KEY (`variant_id`), INDEX `fk_variants_product_idx` (`product_id` ASC) VISIBLE, INDEX `fk_variants_size_idx` (`size_id` ASC) VISIBLE, CONSTRAINT `fk_variants_product` FOREIGN KEY (`product_id`) REFERENCES `opizza`.`products` (`product_id`), CONSTRAINT `fk_variants_size` FOREIGN KEY (`size_id`) REFERENCES `opizza`.`sizes` (`size_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`ingredients` ( `ingredient_id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(50) NOT NULL, `is_spicy` TINYINT DEFAULT FALSE NULL, `is_fish` TINYINT NULL, `if_meat` TINYINT NULL, PRIMARY KEY (`ingredient_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`product_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`product_ingredients` ( `product_id` INT NOT NULL, `ingredient_id` INT NOT NULL, PRIMARY KEY (`product_id`, `ingredient_id`), INDEX `fk_product_ingredients_ingredient_idx` (`ingredient_id` ASC) VISIBLE, CONSTRAINT `fk_product_ingredients_product` FOREIGN KEY (`product_id`) REFERENCES `opizza`.`products` (`product_id`), CONSTRAINT `fk_product_ingredients_ingredient` FOREIGN KEY (`ingredient_id`) REFERENCES `opizza`.`ingredients` (`ingredient_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`tags` ( `tag_id` INT NOT NULL AUTO_INCREMENT, `name` VARCHAR(30) NOT NULL, `color_hex` VARCHAR(7) NULL, PRIMARY KEY (`tag_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`product_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`product_tags` ( `product_id` INT NOT NULL, `tag_id` INT NOT NULL, PRIMARY KEY (`product_id`, `tag_id`), INDEX `fk_product_tags_tag_idx` (`tag_id` ASC) VISIBLE, CONSTRAINT `fk_product_tags_product` FOREIGN KEY (`product_id`) REFERENCES `opizza`.`products` (`product_id`), CONSTRAINT `fk_product_tags_tag` FOREIGN KEY (`tag_id`) REFERENCES `opizza`.`tags` (`tag_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`addresses` ( `addresses_id` INT NOT NULL AUTO_INCREMENT, `user_id` INT UNSIGNED NOT NULL, `city` VARCHAR(30) NULL, `zip_code` VARCHAR(6) NULL, `street` VARCHAR(100) NULL, `house` VARCHAR(10) NULL, `flat` VARCHAR(5) NULL, `type` VARCHAR(64) NULL, `is_default` TINYINT NULL, PRIMARY KEY (`addresses_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`users` ( `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT, `email` VARCHAR(100) NOT NULL, `password` VARCHAR(255) NOT NULL, `first_name` VARCHAR(50) NOT NULL, `last_name` VARCHAR(50) NOT NULL, `phone` VARCHAR(20) NOT NULL, `role` VARCHAR(20) NOT NULL DEFAULT 'GUEST', `avatar_url` VARCHAR(255) NULL, `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `is_active` TINYINT NULL, `default_address_id` INT NULL, PRIMARY KEY (`user_id`), UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE, INDEX `fk_users_addresses_idx` (`default_address_id` ASC) VISIBLE, CONSTRAINT `fk_users_addresses` FOREIGN KEY (`default_address_id`) REFERENCES `opizza`.`addresses` (`addresses_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`carts` ( `carts_id` INT NOT NULL AUTO_INCREMENT, `user_id` INT UNSIGNED NOT NULL UNIQUE, `updated_at` TIMESTAMP NULL, PRIMARY KEY (`carts_id`), INDEX `fk_carts_users_idx` (`user_id` ASC) VISIBLE, CONSTRAINT `fk_carts_users` FOREIGN KEY (`user_id`) REFERENCES `opizza`.`users` (`user_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`cart_items` ( `cart_items_id` INT NOT NULL AUTO_INCREMENT, `cart_id` INT NOT NULL, `product_variant_id` INT NULL, `quantity` INT NOT NULL, PRIMARY KEY (`cart_items_id`), INDEX `fk_cart_items_cart_idx` (`cart_id` ASC) VISIBLE, INDEX `fk_cart_items_variant_idx` (`product_variant_id` ASC) VISIBLE, CONSTRAINT `fk_cart_items_cart` FOREIGN KEY (`cart_id`) REFERENCES `opizza`.`carts` (`carts_id`), CONSTRAINT `fk_cart_items_variant` FOREIGN KEY (`product_variant_id`) REFERENCES `opizza`.`product_variants` (`variant_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`orders` ( `order_id` INT NOT NULL AUTO_INCREMENT, `order_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING', `total_price` DECIMAL(10,2) NOT NULL, `note` TINYTEXT NULL, `delivery_address_id` INT NULL, PRIMARY KEY (`order_id`), INDEX `fk_orders_address_idx` (`delivery_address_id` ASC) VISIBLE, CONSTRAINT `fk_orders_address` FOREIGN KEY (`delivery_address_id`) REFERENCES `opizza`.`addresses` (`addresses_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opizza`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opizza`.`order_items` ( `item_id` INT NOT NULL AUTO_INCREMENT, `order_id` INT NOT NULL, `product_variant_id` INT NULL DEFAULT NULL, `quantity` INT NOT NULL, `price_at_order` DECIMAL(10,2) NOT NULL, `product_name_at_order` VARCHAR(150) NOT NULL, PRIMARY KEY (`item_id`), INDEX `fk_order_items_order_idx` (`order_id` ASC) VISIBLE, INDEX `fk_order_items_variant_idx` (`product_variant_id` ASC) VISIBLE, CONSTRAINT `fk_order_items_order` FOREIGN KEY (`order_id`) REFERENCES `opizza`.`orders` (`order_id`), CONSTRAINT `fk_order_items_variant` FOREIGN KEY (`product_variant_id`) REFERENCES `opizza`.`product_variants` (`variant_id`) ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- ZÁVEREČNÉ ÚPRAVY (ALTER TABLE)
-- -----------------------------------------------------
-- Musí byť na konci, pretože addresses.user_id odkazuje na users.user_id, ktorá musí už existovať
ALTER TABLE `opizza`.`addresses` ADD INDEX `fk_addresses_users_idx` (`user_id` ASC) VISIBLE, ADD CONSTRAINT `fk_addresses_users` FOREIGN KEY (`user_id`) REFERENCES `opizza`.`users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;